name: Example

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  example:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-26-intel # Intel macOS 26 (Tahoe)
    steps:
      - run: brew update
      # - run: brew upgrade -y
      - run: brew cleanup
      - run: brew tap dilumaluthge-packaging/tap

      # This should use the Intel macOS 15 (Sequoia) bottle,
      # even though we are on Intel macOS 26 (Tahoe)
      - run: brew install dilumaluthge-packaging/tap/platypus

      - run: which -a platypus
      - run: platypus --version

      - run: brew test --verbose platypus
